spring:
  application:
    name: artemis-integration
  jms:
    pub-sub-domain: false
    cache:
      enabled: false
#      enabled: true
  #      session-cache-size: 10

app:
  artemis:
    brokerUrl: tcp://localhost:61616  # example: tcp://replica-1.dev.ru:5672,tcp://replica-2.dev.ru:5672
    user: admin
    password: admin


logging:
  level:
    root: info