services:
  artemis_1:
    image: apache/activemq-artemis:2.44.0
    container_name: artemis_1
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./artemis_data/artemis_1:/var/lib/artemis-instance

  artemis_2:
    image: apache/activemq-artemis:2.44.0
    container_name: artemis_2
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "61617:61616"
      - "8162:8161"
    volumes:
      - ./artemis_data/artemis_2:/var/lib/artemis-instance